/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/midway-pacman/02_arcade.glb -o src/components/3d/MidwayCabinet.tsx 
*/

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    arcade_sideL_low: THREE.Mesh
    arcade_sideR_low: THREE.Mesh
    arcade_main_low: THREE.Mesh
    arcade_stick_low: THREE.Mesh
    arcade_buttonB_low: THREE.Mesh
    arcade_buttonT_low: THREE.Mesh
    arcade_panel_low: THREE.Mesh
    arcade_coinSlotR_low: THREE.Mesh
    arcade_coinSlotL_low: THREE.Mesh
    arcade_knobR_low: THREE.Mesh
    arcade_knobL_low: THREE.Mesh
  }
  materials: {
    arcade_MAT: THREE.MeshStandardMaterial
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  animations: any[]
}

export function Model(props: React.ComponentProps<'group'>) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { nodes } = useGLTF('/models/midway-pacman/02_arcade.glb') as any as GLTFResult

  const [maps, setMaps] = React.useState<{ albedo?: THREE.Texture, emission?: THREE.Texture, metallic?: THREE.Texture, normal?: THREE.Texture }>({})

  React.useEffect(() => {
    const loader = new THREE.TextureLoader()
    let isMounted = true

    Promise.all([
      new Promise<THREE.Texture>(resolve => loader.load('/models/midway-pacman/arcade_arcade_MAT_AlbedoTransparency.png', resolve)),
      new Promise<THREE.Texture>(resolve => loader.load('/models/midway-pacman/arcade_arcade_MAT_Emission.png', resolve)),
      new Promise<THREE.Texture>(resolve => loader.load('/models/midway-pacman/arcade_arcade_MAT_MetallicSmoothness.png', resolve)),
      new Promise<THREE.Texture>(resolve => loader.load('/models/midway-pacman/arcade_arcade_MAT_Normal.png', resolve))
    ]).then(([albedo, emission, metallic, normal]) => {
      if (isMounted) {
        // Essential: configure color space for the albedo map
        albedo.colorSpace = THREE.SRGBColorSpace;
        emission.colorSpace = THREE.SRGBColorSpace;

        // GLTF models require flipY to be false for external textures
        albedo.flipY = false;
        emission.flipY = false;
        metallic.flipY = false;
        normal.flipY = false;

        setMaps({ albedo, emission, metallic, normal })
      }
    })

    return () => { isMounted = false }
  }, [])

  const customMaterial = useMemo(() => {
    // Return a base material while loading to prevent invisible meshes
    if (!maps.albedo) return new THREE.MeshStandardMaterial({ color: '#222222' })

    return new THREE.MeshStandardMaterial({
      map: maps.albedo,
      emissiveMap: maps.emission,
      emissive: new THREE.Color('#ffffff'),
      emissiveIntensity: 0.2,
      metalnessMap: maps.metallic,
      normalMap: maps.normal,
      roughness: 0.9,
      metalness: 0.1,
    })
  }, [maps])

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arcade_sideL_low.geometry} material={customMaterial} />
      <mesh geometry={nodes.arcade_sideR_low.geometry} material={customMaterial} />
      <mesh geometry={nodes.arcade_main_low.geometry} material={customMaterial} />
      <mesh geometry={nodes.arcade_stick_low.geometry} material={customMaterial} />
      <mesh geometry={nodes.arcade_buttonB_low.geometry} material={customMaterial} />
      <mesh geometry={nodes.arcade_buttonT_low.geometry} material={customMaterial} />
      <mesh geometry={nodes.arcade_panel_low.geometry} material={customMaterial} />
      <mesh geometry={nodes.arcade_coinSlotR_low.geometry} material={customMaterial} />
      <mesh geometry={nodes.arcade_coinSlotL_low.geometry} material={customMaterial} />
      <mesh geometry={nodes.arcade_knobR_low.geometry} material={customMaterial} />
      <mesh geometry={nodes.arcade_knobL_low.geometry} material={customMaterial} />
    </group>
  )
}

useGLTF.preload('/models/midway-pacman/02_arcade.glb')
